name: DelayedSudo
description: A simple plugin that allowes for sudo commands with a delay.]
author: VisenGames
version: 1.0
main: games.visen.delayedsudo.Main
commands:
  ds:
    description: Main command, send delayed commands.
    usage: /ds {Player}/-c(Console) {time}s/m command -op(Run as op)
    aliases: [delaysudo, dsudo, runlater, delay]
